# Generated by Django 4.0.6 on 2022-11-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_stockactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockactivity',
            name='site_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
