# Generated by Django 4.1.3 on 2022-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
