# Generated by Django 4.0.6 on 2022-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, upload_to='supplier'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='supplier/products'),
        ),
    ]
