# Generated by Django 4.1.3 on 2022-12-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0003_supplierproduct_quality_alter_supplierproduct_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupplierStockActivity",
        ),
    ]
